{-
   AuthServer API
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Account exposing
    ( accountLogoutPost
    , accountPost
    , accountUserGet
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



accountLogoutPost : Maybe Api.Data.LogoutInputModel -> Api.Request ()
accountLogoutPost logoutInputModel_body =
    Api.request
        "POST"
        "/Account/logout"
        []
        []
        []
        (Maybe.map Api.Data.encodeLogoutInputModel logoutInputModel_body)
        (Json.Decode.succeed ())



accountPost : Maybe Api.Data.LoginRequest -> Api.Request ()
accountPost loginRequest_body =
    Api.request
        "POST"
        "/Account"
        []
        []
        []
        (Maybe.map Api.Data.encodeLoginRequest loginRequest_body)
        (Json.Decode.succeed ())



accountUserGet : Api.Request String
accountUserGet =
    Api.request
        "GET"
        "/Account/user"
        []
        []
        []
        Nothing
        Json.Decode.string
