{-
   AuthServer API
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.ApiResource exposing
    ( apiResourceGet
    , apiResourcePost
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



apiResourceGet : Api.Request (List Api.Data.Api.Data.ApiResource)
apiResourceGet =
    Api.request
        "GET"
        "/ApiResource"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.apiResourceDecoderApi.Data.apiResourceDecoder)



apiResourcePost : Maybe Api.Data.ApiResource -> Api.Request ()
apiResourcePost apiResource_body =
    Api.request
        "POST"
        "/ApiResource"
        []
        []
        []
        (Maybe.map Api.Data.encodeApiResource apiResource_body)
        (Json.Decode.succeed ())
