openapi: 3.0.1
info:
  title: AuthServer API
  description: AuthServer Idp
  version: v1
servers:
  - url: https://localhost:3001
paths:
  /Account:
    post:
      tags:
        - Account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Success
  /Account/logout:
    post:
      tags:
        - Account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutInputModel'
          text/json:
            schema:
              $ref: '#/components/schemas/LogoutInputModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/LogoutInputModel'
      responses:
        '200':
          description: Success
  /Account/user:
    get:
      tags:
        - Account
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
  /ApiResource:
    get:
      tags:
        - ApiResource
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiResourceDto'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiResourceDto'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiResourceDto'
    post:
      tags:
        - ApiResource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResourceDto'
          text/json:
            schema:
              $ref: '#/components/schemas/ApiResourceDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ApiResourceDto'
      responses:
        '200':
          description: Success
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        returnUrl:
          type: string
          nullable: true
      additionalProperties: false
    LogoutInputModel:
      type: object
      properties:
        logoutId:
          type: string
          nullable: true
      additionalProperties: false
    ApiResourceSecretDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
          nullable: true
        value:
          type: string
          nullable: true
        expiration:
          type: string
          format: date-time
          nullable: true
        type:
          type: string
          nullable: true
        created:
          type: string
          format: date-time
      additionalProperties: false
    ApiResourceScopeDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        scope:
          type: string
          nullable: true
      additionalProperties: false
    ApiResourceClaimDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        type:
          type: string
          nullable: true
      additionalProperties: false
    ApiResourcePropertyDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        key:
          type: string
          nullable: true
        value:
          type: string
          nullable: true
      additionalProperties: false
    ApiResourceDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        enabled:
          type: boolean
        name:
          type: string
          nullable: true
        displayName:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        allowedAccessTokenSigningAlgorithms:
          type: string
          nullable: true
        showInDiscoveryDocument:
          type: boolean
        secrets:
          type: array
          items:
            $ref: '#/components/schemas/ApiResourceSecretDto'
          nullable: true
        scopes:
          type: array
          items:
            $ref: '#/components/schemas/ApiResourceScopeDto'
          nullable: true
        userClaims:
          type: array
          items:
            $ref: '#/components/schemas/ApiResourceClaimDto'
          nullable: true
        properties:
          type: array
          items:
            $ref: '#/components/schemas/ApiResourcePropertyDto'
          nullable: true
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
          nullable: true
        lastAccessed:
          type: string
          format: date-time
          nullable: true
        nonEditable:
          type: boolean
      additionalProperties: false