openapi: 3.0.1
info:
  title: AuthServer API
  description: AuthServer Idp
  version: v1
servers:
  - url: https://localhost/api
paths:
  /Account:
    post:
      tags:
        - Account
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Success
  /Account/logout:
    post:
      tags:
        - Account
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/LogoutInputModel'
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutInputModel'
          text/json:
            schema:
              $ref: '#/components/schemas/LogoutInputModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/LogoutInputModel'
      responses:
        '200':
          description: Success
  /Account/user:
    get:
      tags:
        - Account
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UserDto'
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
            text/json:
              schema:
                $ref: '#/components/schemas/UserDto'
  /Account/isSignedIn:
    get:
      tags:
        - Account
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: boolean
            application/json:
              schema:
                type: boolean
            text/json:
              schema:
                type: boolean
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        returnUrl:
          type: string
          nullable: true
      additionalProperties: false
    LogoutInputModel:
      type: object
      properties:
        logoutId:
          type: string
          nullable: true
      additionalProperties: false
    UserDto:
      type: object
      properties:
        id:
          type: string
          nullable: true
          readOnly: true
        userName:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        emailConfirmed:
          type: boolean
        phoneNumber:
          type: string
          nullable: true
        phoneNumberConfirmed:
          type: boolean
        twoFactorEnabled:
          type: boolean
      additionalProperties: false