version: '3.7'

services:

  db:
    image: mariadb:10.3.9
    restart: always
    ports:
      - "3306"
    volumes: 
      - "~/.mysql:/var/lib/mysql"
    env_file:
      - db.env
  
  web:
    build: .
    ports:
      - "8001:443"
    depends_on:
      - "db"
    volumes: 
      - "./Certificates:/certificates"
      - "${HOME}/.aspnet/https:/https/"
    env_file:
      - web.env


networks:
  frontend:
    name: custom_frontend
  backend:
    name: custom_backend
