-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.EmailServerDto exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


host : SelectionSet (Maybe String) Api.Object.EmailServerDto
host =
    Object.selectionForField "(Maybe String)" "host" [] (Decode.string |> Decode.nullable)


port_ : SelectionSet (Maybe ScalarCodecs.Port) Api.Object.EmailServerDto
port_ =
    Object.selectionForField "(Maybe ScalarCodecs.Port)" "port" [] (ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecPort |> .decoder |> Decode.nullable)


userName : SelectionSet (Maybe String) Api.Object.EmailServerDto
userName =
    Object.selectionForField "(Maybe String)" "userName" [] (Decode.string |> Decode.nullable)


fromAddress : SelectionSet (Maybe ScalarCodecs.EmailAddress) Api.Object.EmailServerDto
fromAddress =
    Object.selectionForField "(Maybe ScalarCodecs.EmailAddress)" "fromAddress" [] (ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecEmailAddress |> .decoder |> Decode.nullable)


fromDisplayName : SelectionSet (Maybe String) Api.Object.EmailServerDto
fromDisplayName =
    Object.selectionForField "(Maybe String)" "fromDisplayName" [] (Decode.string |> Decode.nullable)
