-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.UserDto exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


id : SelectionSet ScalarCodecs.Uuid Api.Object.UserDto
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| UserName
-}
userName : SelectionSet String Api.Object.UserDto
userName =
    Object.selectionForField "String" "userName" [] Decode.string


{-| Email
-}
email : SelectionSet String Api.Object.UserDto
email =
    Object.selectionForField "String" "email" [] Decode.string


{-| Confirmed E-mail
-}
emailConfirmed : SelectionSet Bool Api.Object.UserDto
emailConfirmed =
    Object.selectionForField "Bool" "emailConfirmed" [] Decode.bool


{-| Phone number
-}
phoneNumber : SelectionSet (Maybe String) Api.Object.UserDto
phoneNumber =
    Object.selectionForField "(Maybe String)" "phoneNumber" [] (Decode.string |> Decode.nullable)


{-| Phone number confirmed
-}
phoneNumberConfirmed : SelectionSet Bool Api.Object.UserDto
phoneNumberConfirmed =
    Object.selectionForField "Bool" "phoneNumberConfirmed" [] Decode.bool


{-| Two factor enabled
-}
twoFactorEnabled : SelectionSet Bool Api.Object.UserDto
twoFactorEnabled =
    Object.selectionForField "Bool" "twoFactorEnabled" [] Decode.bool


{-| Claims associated with the user
-}
claims :
    SelectionSet decodesTo Api.Object.UserClaimDto
    -> SelectionSet (List decodesTo) Api.Object.UserDto
claims object____ =
    Object.selectionForCompositeField "claims" [] object____ (Basics.identity >> Decode.list)
