-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type AddRemoveClaimsPayload
    = AddRemoveClaimsPayload


type AuthorizationDto
    = AuthorizationDto


type ClaimDto
    = ClaimDto


type ClientDto
    = ClientDto


type CreateAuthorizationPayload
    = CreateAuthorizationPayload


type CreateClaimPayload
    = CreateClaimPayload


type CreateClientPayload
    = CreateClientPayload


type CreateScopePayload
    = CreateScopePayload


type CreateUserPayload
    = CreateUserPayload


type DeleteEntityByIdPayload
    = DeleteEntityByIdPayload


type EmailServerDto
    = EmailServerDto


type EmailServerPayload
    = EmailServerPayload


type ScopeDto
    = ScopeDto


type UserClaimDto
    = UserClaimDto


type UserDto
    = UserDto
