-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Scalar exposing (Codecs, DateTime(..), EmailAddress(..), Port(..), Uuid(..), defaultCodecs, defineCodecs, unwrapCodecs, unwrapEncoder)

import Graphql.Codec exposing (Codec)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode


type DateTime
    = DateTime String


type EmailAddress
    = EmailAddress String


type Port
    = Port String


type Uuid
    = Uuid String


defineCodecs :
    { codecDateTime : Codec valueDateTime
    , codecEmailAddress : Codec valueEmailAddress
    , codecPort : Codec valuePort
    , codecUuid : Codec valueUuid
    }
    -> Codecs valueDateTime valueEmailAddress valuePort valueUuid
defineCodecs definitions =
    Codecs definitions


unwrapCodecs :
    Codecs valueDateTime valueEmailAddress valuePort valueUuid
    ->
        { codecDateTime : Codec valueDateTime
        , codecEmailAddress : Codec valueEmailAddress
        , codecPort : Codec valuePort
        , codecUuid : Codec valueUuid
        }
unwrapCodecs (Codecs unwrappedCodecs) =
    unwrappedCodecs


unwrapEncoder :
    (RawCodecs valueDateTime valueEmailAddress valuePort valueUuid -> Codec getterValue)
    -> Codecs valueDateTime valueEmailAddress valuePort valueUuid
    -> getterValue
    -> Graphql.Internal.Encode.Value
unwrapEncoder getter (Codecs unwrappedCodecs) =
    (unwrappedCodecs |> getter |> .encoder) >> Graphql.Internal.Encode.fromJson


type Codecs valueDateTime valueEmailAddress valuePort valueUuid
    = Codecs (RawCodecs valueDateTime valueEmailAddress valuePort valueUuid)


type alias RawCodecs valueDateTime valueEmailAddress valuePort valueUuid =
    { codecDateTime : Codec valueDateTime
    , codecEmailAddress : Codec valueEmailAddress
    , codecPort : Codec valuePort
    , codecUuid : Codec valueUuid
    }


defaultCodecs : RawCodecs DateTime EmailAddress Port Uuid
defaultCodecs =
    { codecDateTime =
        { encoder = \(DateTime raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map DateTime
        }
    , codecEmailAddress =
        { encoder = \(EmailAddress raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map EmailAddress
        }
    , codecPort =
        { encoder = \(Port raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Port
        }
    , codecUuid =
        { encoder = \(Uuid raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Uuid
        }
    }
