-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (..)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias DateTime =
    Api.Scalar.DateTime


type alias Uuid =
    Api.Scalar.Uuid


codecs : Api.Scalar.Codecs DateTime Uuid
codecs =
    Api.Scalar.defineCodecs
        { codecDateTime = defaultCodecs.codecDateTime
        , codecUuid = defaultCodecs.codecUuid
        }
