version: '3.7'

services:

  db:
    image: mariadb:10.3.9
    restart: always
    ports:
      - "3306"
    volumes:
      - "auth-server-db:/var/lib/mysql"
    networks:
      - auth-server-backend
    env_file:
      - db.env

  web:
    build: ../
    ports:
      - "8001:443"
    depends_on:
      - "db"
    volumes:
      - "./OpenSsl:/certificates"
      - "./OpenSsl:/https/"
    networks:
      - auth-server-backend
      - auth-server-frontend
    env_file:
      - web.env

volumes:
  auth-server-db:

networks:
  auth-server-frontend:
  auth-server-backend:
