version: '3.7'

services:

  db:
    image: mariadb:10.3.9
    restart: always
    expose:
      - "3306"
    volumes:
      - "auth-server-db:/var/lib/mysql"
    networks:
      - auth-server-backend

  web:
    build: ../
    expose:
      - "443"
    depends_on:
      - "db"
    volumes:
      - "../Certificates:/certificates"
      - "../Certificates:/https/"
    networks:
      - auth-server-backend
      - auth-server-frontend

volumes:
  auth-server-db:

networks:
  auth-server-frontend:
  auth-server-backend:
