version: '3.7'

services:

  # Nginx image
  nginx:
    image: nginx:stable-alpine
    volumes:
      #- /etc/letsencrypt:/etc/letsencrypt:ro
      - ../Certificates:/etc/ssl/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
    expose:
      - 80
      - 443
    networks:
      - auth-server-frontend
    restart: unless-stopped

  db:
    image: mariadb:10.3.9
    restart: always
    expose:
      - 3306
    volumes:
      - auth-server-db:/var/lib/mysql
    networks:
      - auth-server-backend
    restart: unless-stopped

  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    expose:
      - 5001
    volumes:
      - ../Certificates:/certificates:ro
    networks:
      - auth-server-backend
      - auth-server-frontend
    restart: unless-stopped

  # DuckDNS image
  # duckdns:
  #  image: linuxserver/duckdns
  #  restart: unless-stopped

volumes:
  auth-server-db:

networks:
  auth-server-frontend:
  auth-server-backend:
