version: '3.7'

services:

  nginx:
    ports:
      - 8000:80
      - 4433:443

  db:
    ports:
      - "3306"
    env_file:
      - secret.db.env

  web:
    env_file:
      - secret.web.env

  #duckdns:
  #  env_file:
  #    - secret.duck.env
