{-
   AuthServer API
   AuthServer Idp

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.ApiResource exposing (ApiResource, decoder, encode, encodeWithTag, toString)

import Data.ApiResourceSecret as ApiResourceSecret exposing (ApiResourceSecret)
import Data.ApiResourceScope as ApiResourceScope exposing (ApiResourceScope)
import Data.ApiResourceClaim as ApiResourceClaim exposing (ApiResourceClaim)
import Data.ApiResourceProperty as ApiResourceProperty exposing (ApiResourceProperty)
import DateTime exposing (DateTime)
import DateTime exposing (DateTime)
import DateTime exposing (DateTime)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias ApiResource =
    { id : Maybe (Int)
    , enabled : Maybe (Bool)
    , name : (Maybe String)
    , displayName : (Maybe String)
    , description : (Maybe String)
    , allowedAccessTokenSigningAlgorithms : (Maybe String)
    , showInDiscoveryDocument : Maybe (Bool)
    , secrets : (Maybe (List ApiResourceSecret))
    , scopes : (Maybe (List ApiResourceScope))
    , userClaims : (Maybe (List ApiResourceClaim))
    , properties : (Maybe (List ApiResourceProperty))
    , created : Maybe (DateTime)
    , updated : (Maybe DateTime)
    , lastAccessed : (Maybe DateTime)
    , nonEditable : Maybe (Bool)
    }


decoder : Decoder ApiResource
decoder =
    Decode.succeed ApiResource
        |> optional "id" (Decode.nullable Decode.int) Nothing
        |> optional "enabled" (Decode.nullable Decode.bool) Nothing
        |> optional "name" (Decode.nullable Decode.string) Nothing
        |> optional "displayName" (Decode.nullable Decode.string) Nothing
        |> optional "description" (Decode.nullable Decode.string) Nothing
        |> optional "allowedAccessTokenSigningAlgorithms" (Decode.nullable Decode.string) Nothing
        |> optional "showInDiscoveryDocument" (Decode.nullable Decode.bool) Nothing
        |> optional "secrets" (Decode.nullable (Decode.list ApiResourceSecret.decoder)) Nothing
        |> optional "scopes" (Decode.nullable (Decode.list ApiResourceScope.decoder)) Nothing
        |> optional "userClaims" (Decode.nullable (Decode.list ApiResourceClaim.decoder)) Nothing
        |> optional "properties" (Decode.nullable (Decode.list ApiResourceProperty.decoder)) Nothing
        |> optional "created" (Decode.nullable DateTime.decoder) Nothing
        |> optional "updated" (Decode.nullable DateTime.decoder) Nothing
        |> optional "lastAccessed" (Decode.nullable DateTime.decoder) Nothing
        |> optional "nonEditable" (Decode.nullable Decode.bool) Nothing



encode : ApiResource -> Encode.Value
encode =
    Encode.object << encodePairs


encodeWithTag : ( String, String ) -> ApiResource -> Encode.Value
encodeWithTag (tagField, tag) model =
    Encode.object <| encodePairs model ++ [ ( tagField, Encode.string tag ) ]


encodePairs : ApiResource -> List (String, Encode.Value)
encodePairs model =
    [ ( "id", Maybe.withDefault Encode.null (Maybe.map Encode.int model.id) )
    , ( "enabled", Maybe.withDefault Encode.null (Maybe.map Encode.bool model.enabled) )
    , ( "name", Maybe.withDefault Encode.null (Maybe.map Encode.string model.name) )
    , ( "displayName", Maybe.withDefault Encode.null (Maybe.map Encode.string model.displayName) )
    , ( "description", Maybe.withDefault Encode.null (Maybe.map Encode.string model.description) )
    , ( "allowedAccessTokenSigningAlgorithms", Maybe.withDefault Encode.null (Maybe.map Encode.string model.allowedAccessTokenSigningAlgorithms) )
    , ( "showInDiscoveryDocument", Maybe.withDefault Encode.null (Maybe.map Encode.bool model.showInDiscoveryDocument) )
    , ( "secrets", Maybe.withDefault Encode.null (Maybe.map (Encode.list ApiResourceSecret.encode) model.secrets) )
    , ( "scopes", Maybe.withDefault Encode.null (Maybe.map (Encode.list ApiResourceScope.encode) model.scopes) )
    , ( "userClaims", Maybe.withDefault Encode.null (Maybe.map (Encode.list ApiResourceClaim.encode) model.userClaims) )
    , ( "properties", Maybe.withDefault Encode.null (Maybe.map (Encode.list ApiResourceProperty.encode) model.properties) )
    , ( "created", Maybe.withDefault Encode.null (Maybe.map DateTime.encode model.created) )
    , ( "updated", Maybe.withDefault Encode.null (Maybe.map DateTime.encode model.updated) )
    , ( "lastAccessed", Maybe.withDefault Encode.null (Maybe.map DateTime.encode model.lastAccessed) )
    , ( "nonEditable", Maybe.withDefault Encode.null (Maybe.map Encode.bool model.nonEditable) )
    ]



toString : ApiResource -> String
toString =
    Encode.encode 0 << encode




