{-
   AuthServer API
   AuthServer Idp

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.ApiResourceSecretDto exposing (ApiResourceSecretDto, decoder, encode, encodeWithTag, toString)

import DateTime exposing (DateTime)
import DateTime exposing (DateTime)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias ApiResourceSecretDto =
    { id : Maybe (Int)
    , description : (Maybe String)
    , value : (Maybe String)
    , expiration : (Maybe DateTime)
    , type_ : (Maybe String)
    , created : Maybe (DateTime)
    }


decoder : Decoder ApiResourceSecretDto
decoder =
    Decode.succeed ApiResourceSecretDto
        |> optional "id" (Decode.nullable Decode.int) Nothing
        |> optional "description" (Decode.nullable Decode.string) Nothing
        |> optional "value" (Decode.nullable Decode.string) Nothing
        |> optional "expiration" (Decode.nullable DateTime.decoder) Nothing
        |> optional "type" (Decode.nullable Decode.string) Nothing
        |> optional "created" (Decode.nullable DateTime.decoder) Nothing



encode : ApiResourceSecretDto -> Encode.Value
encode =
    Encode.object << encodePairs


encodeWithTag : ( String, String ) -> ApiResourceSecretDto -> Encode.Value
encodeWithTag (tagField, tag) model =
    Encode.object <| encodePairs model ++ [ ( tagField, Encode.string tag ) ]


encodePairs : ApiResourceSecretDto -> List (String, Encode.Value)
encodePairs model =
    [ ( "id", Maybe.withDefault Encode.null (Maybe.map Encode.int model.id) )
    , ( "description", Maybe.withDefault Encode.null (Maybe.map Encode.string model.description) )
    , ( "value", Maybe.withDefault Encode.null (Maybe.map Encode.string model.value) )
    , ( "expiration", Maybe.withDefault Encode.null (Maybe.map DateTime.encode model.expiration) )
    , ( "type", Maybe.withDefault Encode.null (Maybe.map Encode.string model.type_) )
    , ( "created", Maybe.withDefault Encode.null (Maybe.map DateTime.encode model.created) )
    ]



toString : ApiResourceSecretDto -> String
toString =
    Encode.encode 0 << encode




