{-
   AuthServer API
   AuthServer Idp

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.ApiResourceScopeDto exposing (ApiResourceScopeDto, decoder, encode, encodeWithTag, toString)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias ApiResourceScopeDto =
    { id : Maybe (Int)
    , scope : (Maybe String)
    }


decoder : Decoder ApiResourceScopeDto
decoder =
    Decode.succeed ApiResourceScopeDto
        |> optional "id" (Decode.nullable Decode.int) Nothing
        |> optional "scope" (Decode.nullable Decode.string) Nothing



encode : ApiResourceScopeDto -> Encode.Value
encode =
    Encode.object << encodePairs


encodeWithTag : ( String, String ) -> ApiResourceScopeDto -> Encode.Value
encodeWithTag (tagField, tag) model =
    Encode.object <| encodePairs model ++ [ ( tagField, Encode.string tag ) ]


encodePairs : ApiResourceScopeDto -> List (String, Encode.Value)
encodePairs model =
    [ ( "id", Maybe.withDefault Encode.null (Maybe.map Encode.int model.id) )
    , ( "scope", Maybe.withDefault Encode.null (Maybe.map Encode.string model.scope) )
    ]



toString : ApiResourceScopeDto -> String
toString =
    Encode.encode 0 << encode




