{-
   AuthServer API
   AuthServer Idp

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.ApiResourceProperty exposing (ApiResourceProperty, decoder, encode, encodeWithTag, toString)

import Data.ApiResource as ApiResource exposing (ApiResource)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias ApiResourceProperty =
    { id : Maybe (Int)
    , key : (Maybe String)
    , value : (Maybe String)
    , apiResourceId : Maybe (Int)
    , apiResource : Maybe (ApiResource)
    }


decoder : Decoder ApiResourceProperty
decoder =
    Decode.succeed ApiResourceProperty
        |> optional "id" (Decode.nullable Decode.int) Nothing
        |> optional "key" (Decode.nullable Decode.string) Nothing
        |> optional "value" (Decode.nullable Decode.string) Nothing
        |> optional "apiResourceId" (Decode.nullable Decode.int) Nothing
        |> optional "apiResource" (Decode.nullable ApiResource.decoder) Nothing



encode : ApiResourceProperty -> Encode.Value
encode =
    Encode.object << encodePairs


encodeWithTag : ( String, String ) -> ApiResourceProperty -> Encode.Value
encodeWithTag (tagField, tag) model =
    Encode.object <| encodePairs model ++ [ ( tagField, Encode.string tag ) ]


encodePairs : ApiResourceProperty -> List (String, Encode.Value)
encodePairs model =
    [ ( "id", Maybe.withDefault Encode.null (Maybe.map Encode.int model.id) )
    , ( "key", Maybe.withDefault Encode.null (Maybe.map Encode.string model.key) )
    , ( "value", Maybe.withDefault Encode.null (Maybe.map Encode.string model.value) )
    , ( "apiResourceId", Maybe.withDefault Encode.null (Maybe.map Encode.int model.apiResourceId) )
    , ( "apiResource", Maybe.withDefault Encode.null (Maybe.map ApiResource.encode model.apiResource) )
    ]



toString : ApiResourceProperty -> String
toString =
    Encode.encode 0 << encode




