{-
   AuthServer API
   AuthServer Idp

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.ScopeDto exposing (ScopeDto, decoder, encode, encodeWithTag, toString)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias ScopeDto =
    { name : (Maybe String)
    , displayName : (Maybe String)
    }


decoder : Decoder ScopeDto
decoder =
    Decode.succeed ScopeDto
        |> optional "name" (Decode.nullable Decode.string) Nothing
        |> optional "displayName" (Decode.nullable Decode.string) Nothing



encode : ScopeDto -> Encode.Value
encode =
    Encode.object << encodePairs


encodeWithTag : ( String, String ) -> ScopeDto -> Encode.Value
encodeWithTag (tagField, tag) model =
    Encode.object <| encodePairs model ++ [ ( tagField, Encode.string tag ) ]


encodePairs : ScopeDto -> List (String, Encode.Value)
encodePairs model =
    [ ( "name", Maybe.withDefault Encode.null (Maybe.map Encode.string model.name) )
    , ( "displayName", Maybe.withDefault Encode.null (Maybe.map Encode.string model.displayName) )
    ]



toString : ScopeDto -> String
toString =
    Encode.encode 0 << encode




