{-
   AuthServer API
   AuthServer Idp

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.Account exposing (apiAccountIsSignedInGet, apiAccountLogoutPost, apiAccountPost, apiAccountUserGet)

import Data.UserDto as UserDto exposing (UserDto)
import Data.LoginRequest as LoginRequest exposing (LoginRequest)
import Dict
import Http
import Json.Decode as Decode
import Url.Builder as Url




basePath : String
basePath =
    "https://localhost/api"


apiAccountIsSignedInGet :
    { onSend : Result Http.Error Bool -> msg





    }
    -> Cmd msg
apiAccountIsSignedInGet params =
    Http.request
        { method = "GET"
        , headers = List.filterMap identity []
        , url = Url.crossOrigin basePath
            ["api", "Account", "isSignedIn"]
            (List.filterMap identity [])
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend Decode.bool
        , timeout = Just 30000
        , tracker = Nothing
        }


apiAccountLogoutPost :
    { onSend : Result Http.Error () -> msg




    , logoutId : Maybe (String)
    }
    -> Cmd msg
apiAccountLogoutPost params =
    Http.request
        { method = "POST"
        , headers = List.filterMap identity []
        , url = Url.crossOrigin basePath
            ["api", "Account", "logout"]
            (List.filterMap identity [Maybe.map (Url.string "LogoutId" << identity) params.logoutId])
        , body = Http.emptyBody
        , expect = Http.expectWhatever params.onSend
        , timeout = Just 30000
        , tracker = Nothing
        }


apiAccountPost :
    { onSend : Result Http.Error () -> msg


    , body : Maybe LoginRequest


    }
    -> Cmd msg
apiAccountPost params =
    Http.request
        { method = "POST"
        , headers = List.filterMap identity []
        , url = Url.crossOrigin basePath
            ["api", "Account"]
            (List.filterMap identity [])
        , body = Maybe.withDefault Http.emptyBody <| Maybe.map (Http.jsonBody << LoginRequest.encode) params.body
        , expect = Http.expectWhatever params.onSend
        , timeout = Just 30000
        , tracker = Nothing
        }


apiAccountUserGet :
    { onSend : Result Http.Error UserDto -> msg





    }
    -> Cmd msg
apiAccountUserGet params =
    Http.request
        { method = "GET"
        , headers = List.filterMap identity []
        , url = Url.crossOrigin basePath
            ["api", "Account", "user"]
            (List.filterMap identity [])
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend UserDto.decoder
        , timeout = Just 30000
        , tracker = Nothing
        }
