{-
   AuthServer API
   AuthServer Idp

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.Scopes exposing (scopesGet, scopesPut)

import Data.ScopeDto as ScopeDto exposing (ScopeDto)
import Dict
import Http
import Json.Decode as Decode
import Url.Builder as Url




basePath : String
basePath =
    "https://localhost"


scopesGet :
    { onSend : Result Http.Error (List ScopeDto) -> msg





    }
    -> Cmd msg
scopesGet params =
    Http.request
        { method = "GET"
        , headers = List.filterMap identity []
        , url = Url.crossOrigin basePath
            ["Scopes"]
            (List.filterMap identity [])
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend (Decode.list ScopeDto.decoder)
        , timeout = Just 30000
        , tracker = Nothing
        }


scopesPut :
    { onSend : Result Http.Error Bool -> msg




    , name : Maybe (String)    , displayName : Maybe (String)
    }
    -> Cmd msg
scopesPut params =
    Http.request
        { method = "PUT"
        , headers = List.filterMap identity []
        , url = Url.crossOrigin basePath
            ["Scopes"]
            (List.filterMap identity [Maybe.map (Url.string "Name" << identity) params.name, Maybe.map (Url.string "DisplayName" << identity) params.displayName])
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend Decode.bool
        , timeout = Just 30000
        , tracker = Nothing
        }
