{-
   AuthServer API
   AuthServer Idp

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.Scopes exposing (apiScopesGet, apiScopesPut)

import Data.ScopeDto as ScopeDto exposing (ScopeDto)
import Dict
import Http
import Json.Decode as Decode
import Url.Builder as Url




basePath : String
basePath =
    "https://localhost/api"


apiScopesGet :
    { onSend : Result Http.Error (List ScopeDto) -> msg





    }
    -> Cmd msg
apiScopesGet params =
    Http.request
        { method = "GET"
        , headers = List.filterMap identity []
        , url = Url.crossOrigin basePath
            ["api", "Scopes"]
            (List.filterMap identity [])
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend (Decode.list ScopeDto.decoder)
        , timeout = Just 30000
        , tracker = Nothing
        }


apiScopesPut :
    { onSend : Result Http.Error Bool -> msg


    , body : Maybe ScopeDto


    }
    -> Cmd msg
apiScopesPut params =
    Http.request
        { method = "PUT"
        , headers = List.filterMap identity []
        , url = Url.crossOrigin basePath
            ["api", "Scopes"]
            (List.filterMap identity [])
        , body = Maybe.withDefault Http.emptyBody <| Maybe.map (Http.jsonBody << ScopeDto.encode) params.body
        , expect = Http.expectJson params.onSend Decode.bool
        , timeout = Just 30000
        , tracker = Nothing
        }
