-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.AuthorizationDto exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The Id of the api resource
-}
id : SelectionSet Api.ScalarCodecs.Uuid Api.Object.AuthorizationDto
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| Is the resource enabled
-}
application :
    SelectionSet decodesTo Api.Object.ClientDto
    -> SelectionSet decodesTo Api.Object.AuthorizationDto
application object____ =
    Object.selectionForCompositeField "application" [] object____ Basics.identity


{-| The name of the resource
-}
scopes : SelectionSet (List String) Api.Object.AuthorizationDto
scopes =
    Object.selectionForField "(List String)" "scopes" [] (Decode.string |> Decode.list)


{-| The display name used in consent screens
-}
status : SelectionSet String Api.Object.AuthorizationDto
status =
    Object.selectionForField "String" "status" [] Decode.string


{-| The description of the api resource
-}
subject : SelectionSet String Api.Object.AuthorizationDto
subject =
    Object.selectionForField "String" "subject" [] Decode.string


{-| The secrets registered for the resource
-}
creationDate : SelectionSet (Maybe Api.ScalarCodecs.DateTime) Api.Object.AuthorizationDto
creationDate =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "creationDate" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


{-| The scopes registered for this resource
-}
type_ : SelectionSet (Maybe String) Api.Object.AuthorizationDto
type_ =
    Object.selectionForField "(Maybe String)" "type" [] (Decode.string |> Decode.nullable)
