-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type AuthorizationDto
    = AuthorizationDto


type ClientDto
    = ClientDto


type CreateAuthorizationPayload
    = CreateAuthorizationPayload


type CreateClientPayload
    = CreateClientPayload


type CreateScopePayload
    = CreateScopePayload


type CreateUserPayload
    = CreateUserPayload


type DeleteEntityByIdPayload
    = DeleteEntityByIdPayload


type ScopeDto
    = ScopeDto


type UserDto
    = UserDto
